manual: False
toml_path: /gpfs/home/asun/jin_lab/state/debug/STATE/state/test_boli/Boli_Perturb_CTX_edit_L6_hvg.toml
manual_control: False
seed: 1
max_heldout_fraction_per_covariate: 0.3
max_heldout_covariates: 100